---
title: "Map of EMCR locations"
output:
  html_document:
    theme: flatly
    toc: yes
    toc_float: yes
---

Libraries Required

```{r, message = FALSE}
library(ggmap)
```

Load our location data

```{r}
#this is a spreadsheet with the 23 EMCR presenters (both talks and posters) pulled from the ASSC 2021 conference booklet which can be found at: https://www.seedpartnership.org.au/wp-content/uploads/2021/10/ASSC-2021-Program-Booklet.pdf

EMCRlocationdata <- read.csv("ASSC EMCR talks by theme.csv")
```

Constructing world map for base

```{r}
WorldMap <- ggplot() + borders("world", colour="grey", fill="#C7DBC8") + theme_classic()
WorldMap
```
Add our location points to world map

```{r}
MyMap <- WorldMap +
  geom_point(aes(x=Long, y=Lat, size = SpeciesNumber), data = EMCRlocationdata, alpha=0.65, shape=16, stroke = 2) +
  ylim(-65,90) +
  theme(axis.text=element_text(size=40),
        axis.title=element_text(size=55)) +
  scale_size_continuous(range = c(3, 9)) +
  labs(y = "Latitude (degrees)", x = "Longitude (degrees)")
MyMap
```

Now creating a map of Australia as an inlay for this world map

```{r}
AusMap <- WorldMap + 
  geom_point(aes(x=Long, y=Lat, colour = Theme, shape = Theme, stroke = Theme), data = EMCRlocationdata, size = 14, alpha = 0.65) +
  scale_colour_manual(values = c("hotpink2", "cyan4", "chartreuse3", "darkorange")) +
  scale_shape_manual(values = c(15,16,3,4)) +
  scale_discrete_manual(
    aesthetics = "stroke",
    values = c(1,1,4,4)
  ) +
  ylim(-45,-11) +
  xlim(110, 155) +
  theme(axis.text=element_text(size=40),
        axis.title=element_text(size=55)) +
  labs(y = "Latitude (degrees)", x = "Longitude (degrees)")
AusMap
```

Save plots

```{r}
ggsave(plot=MyMap, device= "tiff", file='Outputs/worldmaplocations.tiff', width=20, height =10)

ggsave(plot=AusMap, device= "tiff", file='Outputs/ausmaplocations.tiff', width=20, height =16)
```

